AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  lambdaCumulocityBot:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: alarms.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: ''
      MemorySize: 256
      Timeout: 3
      Role: 'arn:aws:iam::540971695762:role/service-role/myRole'
